name = "sublink"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "sublink-db" # <-- 请确保这是您在Cloudflare上创建的D1数据库的名称
database_id = "c651f7b8-0714-4bc0-8094-46eb911e8bc3" # <-- 请务必将这里替换为您真实D1数据库的ID


